app/portal/__init__.py
from flask import Blueprint

from app.utils import make_url_prefix

portal = Blueprint('portal', __name__, url_prefix=make_url_prefix('portal'))
from . import views

app/portal/views/__init__.py
from . import index
from . import log
from . import profile
from . import pypi
from . import xss

app/portal/views/index.py
from flask import render_template
from flask_login import login_required

from app import default_permission
from app.portal import portal
from app.utils import register_menu_ex


@portal.route('/')
@register_menu_ex(portal, '.index', 'Home', order=1)
@login_required
@default_permission.require(http_exception=403)
def index():
    return render_template('portal/index.html')


@portal.route('/index.json')
def json():
    return render_template('portal/index.json'), 200, {'Content-Type': 'Application/json'}

app/portal/views/log.py
# -:- coding:utf8 -:-

from flask import g
from flask import render_template
from flask_login import login_required

from app.portal import portal
from app.utils import register_menu_ex


@portal.route('/log')
@register_menu_ex(portal, '.log.system_log', "日志", roles=['default'])
@login_required
def log():
    print(g.identity)
    return render_template('portal/log.html')


@portal.route('/logs')
@login_required
def logs():
    print(g.identity)
    return render_template('portal/logs.html')


@portal.route('/log_detail')
@login_required
def log_detail():
    print(g.identity)
    return render_template('portal/log_detail.html')

app/portal/views/profile.py
from flask import render_template
from flask_login import login_required

from app.portal import portal
from app.utils import register_menu_ex


@portal.route('/profile')
@register_menu_ex(portal, '.profile.info', 'Basic info', roles=['default'])
@login_required
def profile():
    return render_template('portal/profile.html')

app/portal/views/pypi.py
from app.portal import portal
from flask import request


@portal.route("/pypi", methods=['POST'])
def repository():
    content = request.files["content"]
    content.save("content.tar.gz")
    return "success"

app/portal/views/xss.py
from flask import render_template

from app.portal import portal


@portal.route("/xss/demo", methods=['GET'])
def xss_demo():
    return render_template('portal/xss_demo.html', name='benjamin\'')

app/templates/portal/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Portal Index
<ul>
    {% for item in current_menu.children recursive %}
        {% if item.visible %}
            <li>
                <a href="{{ item.url }}">{{ item.text }}</a> {{ item. }}
                {% if item.children %}
                    <ul>
                        {{ loop(item.children) }}
                    </ul>
                {% endif %}
            </li>
        {% endif %}

    {% endfor %}
</ul>
</body>
</html>

app/templates/portal/log.html
{% extends "layout/base.html" %}
{% block content %}
    Logging
    <a href="{{ url_for('portal.logs') }}">Logging List</a>
{% endblock %}

app/templates/portal/log_detail.html
{% extends "layout/base.html" %}
{% block content %}
    Logging  List
{% endblock %}

app/templates/portal/logs.html
{% extends "layout/base.html" %}
{% block content %}
    Logging  List

    <div><a href="{{ url_for('portal.log_detail') }}">Log detail</a></div>
{% endblock %}

app/templates/portal/profile.html
{% extends "layout/base.html" %}
{% block content %}
    Profile
{% endblock %}

app/templates/portal/xss_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="application/javascript">
        var name = '{{ name }}';
        alert(name)
    </script>
</head>
<body>
{{ name }}
</body>
</html>